### ISSUE TITLE
Learn session page links dark mode styles needs adjustment

### ISSUE THREAD

**Issue by thefrontendwizard** [reflexjs/reflex#1]
![image](https://user-images.githubusercontent.com/1124448/85112793-80e90180-b216-11ea-8465-2fcc5f39ef4c.png)

So the selected page button is white and the link color is also white on the dark mode.

Tested it both on chrome and firefox.

**Comment by arshad** [comment]
Fixed in https://github.com/reflexjs/reflex/commit/ac337d4d71f256cca67c6cd039b538cff5e13367. Thank you.
