### ISSUE TITLE
Team section not working

### ISSUE THREAD

**Issue by TanviPriyadarshini** [reflexjs/reflex#10]
[https://codesandbox.io/s/github/TanviPriyadarshini/reflexjs-test](url)

Tried implementing one of the team blocks but doesn't work.

**Comment by jacine** [comment]
Hi @TanviPriyadarshini!

I just took a look at your code. Looks like you just need to adjust the way you are referencing the blocks in your `content/pages/index.mdx`. The block should be referenced without the path:

```diff
- <Block src="/content/blocks/teams" />
+ <Block src="teams" />
```

PS - The header and footer are automatically added to the page, so you don't need to add these.

HTH,
Jacine

**Comment by arshad** [comment]
@TanviPriyadarshini did you figure this out? Happy to help if you have any other questions.

**Comment by TanviPriyadarshini** [comment]
@jacine Thanks for your help, works for me now!
@arshad works now thanks
