### ISSUE TITLE
Changing header and footer menu styles

### ISSUE THREAD

**Issue by mattmaker** [reflexjs/reflex#101]
I have a dark background image in my hero block, and a white background on the footer. I wanted to change the header menu color to white so I shadowed the `nav-menu.js` file. I created the file `src/@reflexjs/gatsby-theme-nav/nav-menu.js` and then changed the color to white on line 26 like this:
```
 const linkStyle = {
    color: "#fff",
    ...
  }
```

But it changed the menu in the footer to white as well, which I want to keep black.

I'm sure there is a better solution to this. Any help?

Thanks.

**Comment by arshad** [comment]
Can you use the `name` props to do some conditional styles? https://github.com/reflexjs/reflex/blob/master/packages/gatsby-theme-nav/src/nav-menu.js#L189

**Comment by mattmaker** [comment]
Not sure how to do that 😅

**Comment by arshad** [comment]
You can also do this by passing styles to the `NavMenu` using the `sx` props.

Here's an example: https://reflex-menu-styles.netlify.app

I created a sample repo here: https://github.com/arshad/reflex-menu-styles

See this commit for the additional styles added via `sx` props: https://github.com/arshad/reflex-menu-styles/commit/810ca33341985ccdcb9b852558f7dd4c45f24c9c?branch=810ca33341985ccdcb9b852558f7dd4c45f24c9c&diff=unified#diff-699e30c95997e6e078f5469442d9934d38e0a57f6ef780d7f6b7394a66a2d49d

**Comment by mattmaker** [comment]
That worked. Thanks!
