### ISSUE TITLE
How to add a layout.js and edit markdown styling?

### ISSUE THREAD

**Issue by benbehringer** [reflexjs/reflex#104]
Hi,

To customize markdown styling, I followed [this doc](https://www.gatsbyjs.com/docs/mdx/customizing-components/) and added a layout.js. Yet, it seems like the layout.js at `src/components/layout.js` is not loaded. I also tried `src/@reflexjs/gatsby-theme-core` without any luck. Any hints?

Thanks,
Ben

**Comment by arshad** [comment]
For Reflex, you create `src/@reflexjs/gatsby-theme-core/mdx-components.js`.

See https://github.com/reflexjs/reflex/blob/master/packages/gatsby-theme-core/src/mdx-components.js

**Comment by benbehringer** [comment]
Thanks! Adding `src/@reflexjs/gatsby-theme-core/mdx-components.js` makes any content from pages disappear and only content of posts is visible. What am I doing wrong?

**Comment by arshad** [comment]
Ah I see. So the base starter is already shadowing this file and adding some additional components to it. This is probably why the error when you're shadowing it again.

Can you instead shadow `src/@reflexjs/gatsby-theme-base/mdx-component.js`?

See https://github.com/reflexjs/reflex/blob/master/packages/gatsby-theme-base/src/%40reflexjs/gatsby-theme-core/mdx-components.js

or keep `src/@reflexjs/gatsby-theme-core/mdx-components.js` and add the code from src/@reflexjs/gatsby-theme-core/mdx-components.js to it.

```jsx
// src/@reflexjs/gatsby-theme-core/mdx-components.js
import { MDXComponents as CoreMDXComponents } from "@reflexjs/gatsby-theme-core/src/mdx-components"
import { Block } from "@reflexjs/gatsby-theme-block"
import { Image } from "@reflexjs/gatsby-plugin-image"
import { NavMenu } from "@reflexjs/gatsby-theme-nav"

export const MDXComponents = {
  ...CoreMDXComponents,
  Block,
  Image,
  NavMenu,
  img: Image,

 // Add or overwrite components here
}
```

**Comment by benbehringer** [comment]
Thanks! I shadowed `src/@reflexjs/gatsby-theme-core/mdx-components.js` as suggested and it works like a charm!
