### ISSUE TITLE
Blog: Adding post-footer.mdx block results in TypeError

### ISSUE THREAD

**Issue by benbehringer** [reflexjs/reflex#105]
Hi,

adding `post-footer.mdx` and `post-header.mdx` blocks results in a TypeError:

<img width="1039" alt="Screenshot 2020-10-26 at 22 53 56" src="https://user-images.githubusercontent.com/37022575/97232807-22441d80-17de-11eb-926b-92a2d15a6a48.png">

Thanks!
Ben

**Comment by arshad** [comment]
What’s in post-footer.mdx?

**Comment by benbehringer** [comment]
`Test`

**Comment by arshad** [comment]
Ah you need to export a component. Try:

```jsx
export const PostFooter = () => {
  return <P>Test</P>
}
```

Note: you have access to the post props as well:

```jsx
export const PostFooter = ({ title, slug }) => {
  return <P>{title}</P>
}
```

**Comment by arshad** [comment]
If you want to use markdown in the post footer you can reference a block.

Say you have a `content/blocks/footnote.mdx` block with markdown:

```md
### This is a heading

This is some **markdown** text
```

Then in `post-footer.mdx` you can do:

```jsx
export const PostFooter = () => {
  return <Block src="footnote" />
}
```

**Comment by benbehringer** [comment]
Awesome, thanks!
