### ISSUE TITLE
Imported MDX breaks on empty lines

### ISSUE THREAD

**Issue by markmctamney** [reflexjs/reflex#11]
Given MDX like:

```
# Title for this section

Paragraph of text #1...

Paragraph of text #2...
```

If I use this code directly in the `content/pages` folder, it displays as expected.  But if I move the code to `content/blocks/example.mdx` and use `<Block src="example" />` on a page, then all that displays is the first line of MDX (the `# Title for this section`).  All of the subsequent text is getting chopped off without any error or message why.  Same thing happens if you import the file.

Not sure if this is a greater issue with `gatsby-plugin-mdx` or not, but I would have expected this to work.  Otherwise awesome library though!

**Comment by arshad** [comment]
Oh I've seen this too. Looking into it. Probably something to do about how we are importing blocks.

**Comment by arshad** [comment]
Found a fix. I'll tag a new release. As a temporary fix you can wrap the markdown in a `Div`:

```md
<Div>

# Title for this section

Paragraph of text #1...

Paragraph of text #2...

</Div>
```

**Comment by markmctamney** [comment]
Awesome! Yeah I ended up finding something pretty similar to patch it for now.  So not a huge thing and I'll keep an eye out for the release.  But pretty smooth sailing other than that and already found this super useful.  Looks like a bunch more cool stuff coming too so I'm looking forward to following along and seeing where it goes. Keep up the good work! :)

**Comment by arshad** [comment]
@markmctamney Tagged a new release with the fix. Let me know if this works. Thank you.

**Comment by markmctamney** [comment]
Yep!  All good, everything working as expected now.  Thanks a bunch for the quick fix.
