### ISSUE TITLE
All examples should follow Google accessibility rules

### ISSUE THREAD

**Issue by larsroettig** [reflexjs/reflex#12]
Example-Url:
- https://reflexjs.org/library/blocks/header-01

### Currrent

```
export const SocialLinks = ({ ...props }) => (
  <Grid col="repeat(2, auto)" gap="5" {...props}>
    <A href="https://twitter.com/arshadcn" target="_blank" >
      <Icon name="twitter" size="5" />
      <VisuallyHidden>Follow on Twitter</VisuallyHidden>
    </A>
    <A
      href="https://github.com/reflexjs/reflex"
      target="_blank"
      color="text"
      hoverColor="primary"
    >
      <Icon name="instagram" size="5" />
      <VisuallyHidden>Follow on Instagram</VisuallyHidden>
    </A>
  </Grid>
)
```

### Expected 
```javascript
export const SocialLinks = ({ ...props }) => (
  <Grid col="repeat(2, auto)" gap="5" {...props}>
    <A href="https://twitter.com/arshadcn" target="_blank" aria-label="Follow on Twitter">
      <Icon name="twitter" size="5" />
      <VisuallyHidden>Follow on Twitter</VisuallyHidden>
    </A>
    <A
      href="https://github.com/reflexjs/reflex"
      target="_blank"
      color="text"
      hoverColor="primary"
      aria-label="Follow on Instagram"
    >
      <Icon name="instagram" size="5" />
      <VisuallyHidden>Follow on Instagram</VisuallyHidden>
    </A>
  </Grid>
)
```

### Screenshot
![Screenshot at 00-33-25](https://user-images.githubusercontent.com/5289370/86543590-58544d80-bf20-11ea-9abb-78967c855cff.png)

## Resources
- https://developers.google.com/web/fundamentals/accessibility/semantics-aria/aria-labels-and-relationships
- https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/ARIA_Techniques/Using_the_aria-label_attribute

**Comment by arshad** [comment]
Hmm it looks like this might be coming from the actual site and not the block example. 

I see a few a11y issues with the copy code button and forms let me fix this.

**Comment by arshad** [comment]
OK I fixed this and also added a11y tests to make sure other pages are accessible too.

https://github.com/reflexjs/reflex/blob/master/sites/www/cypress/integration/a11y.spec.js
https://github.com/reflexjs/reflex/blob/master/sites/www/cypress/fixtures/a11y-pages.json

Thank you. This is a nice fix. Appreciate the help.
