### ISSUE TITLE
Error in node creation for @reflexjs/gatsby-theme-doc

### ISSUE THREAD

**Issue by rsexton404** [reflexjs/reflex#123]
Maybe I'm just being impatient to try out an unreleased (?) Gatsby theme, but I get the following error when adding `@reflexjs/gatsby-theme-doc` to the base starter and adding an example MDX file in `content/docs/`.

```
error "@reflexjs/gatsby-theme-doc" threw an error while running the onCreateNode lifecycle:

object null is not iterable (cannot read property Symbol(Symbol.iterator))

  56 |   if (docNode) {
  57 |     const parent = getNode(node.parent)
> 58 |     const [, weight, name] = parent.name.match(/^(\d+)-(.*)/)
     |                              ^
  59 |     actions.createNode({
  60 |       ...docNode,
  61 |       weight: parseInt(weight),


  TypeError: object null is not iterable (cannot read property Symbol(Symbol.iterator))

  - gatsby-node.js:58 Object.exports.onCreateNode
    [eadocs-reflex]/[@reflexjs]/gatsby-theme-doc/gatsby-node.js:58:30
```

Also, I don't see any examples or references to this theme in the docs (as the README.md for the package suggests). If this is still an upcoming feature, that makes perfect sense—and I can't wait to try it when it's ready!

**Comment by rsexton404** [comment]
I think this is caused by not naming the files inside `content/docs` as expected. I've submitted [PR 124](https://github.com/reflexjs/reflex/pull/124), which fixes the issue with the README, but it might be a good idea to handle the case when filenames do not include a "weight."

**Comment by rsexton404** [comment]
BTW, how does the tableOfContents work? And is there a way to specify which nav to use? I'd like to display different sets of pages for documenting different products.

**Comment by arshad** [comment]
Yeah `gatsby-theme-doc` is mainly used for running the docs on reflexjs.org and I've not really tested it on other setups. 

I just merged the PR. Let me know if this fixes the issue.

> BTW, how does the tableOfContents work?

Do you mean the sidebar nav?

This is using https://github.com/reflexjs/reflex/blob/master/sites/www/content/navs/doc.mdx which is being called from https://github.com/reflexjs/reflex/blob/master/packages/gatsby-theme-doc/src/doc-nav.js#L113

I've not looked into it yet but I think if you can set a nav field on the product then pass it as props to doc-nav maybe this could work?

**Comment by arshad** [comment]
OK I looked into it a bit and created an example here:

Demo: https://reflexjs-product-docs.netlify.app
Repo: https://github.com/arshad/reflexjs-product-docs

## How it works

Reflexjs has support for [additional fields](https://reflexjs.org/docs/recipes#additional-fields) that are passed down from frontmatter to the schema. 

1. I created one nav for each doc. See https://github.com/arshad/reflexjs-product-docs/tree/master/content/navs
2. I'm then using additional fields to set the nav name for each product doc.

```
---
title: Product One
excerpt: This is doc for product one.
nav: doc-product-one
---
```

3. I updated `doc.js` and `doc-nav.js` to accept this `nav` as prop.

```jsx
// doc-nav.js
export const DocNav = ({ name, onClick, ...props }) => {
  const [nav] = useNav(name)
}
```

https://github.com/arshad/reflexjs-product-docs/blob/master/src/%40reflexjs/gatsby-theme-doc/doc-nav.js#L112

```jsx
// doc.js
<DocNav name={data.nav} onClick={() => setShowMenu(false)} />
```

https://github.com/arshad/reflexjs-product-docs/blob/e6560305f337f455ce36f3c66b5bb4c0b498cd8d/src/%40reflexjs/gatsby-theme-doc/doc.js#L76

**Comment by rsexton404** [comment]
Wow, thank you for looking into this for me! If I could organize my different product docs into folders (and a few levels of subfolders too), this would be really great for building a large developer portal type of site.

**Comment by rsexton404** [comment]
As it stands, the folders and subfolders do not get translated into routes. So a file in `docs/product-one/guides/01-integration-guide.mdx` would get the route `docs/integration-guide` but another file in `docs/product-two/guides/01-integration-guide.mdx` would get the same route and cause a conflict.

It would be very powerful if a doc file's unique path (including folders and subfolders) could be translated into the route!

**Comment by rsexton404** [comment]
PS: I tried adding two copies of `@reflexjs/gatsby-theme-doc` to my `gatsby-config.js` file with different `contentPath` and `basePath` values, which would allow me to segment the two product routes more, but it doesn't handle subfolders within the product folder. I imagine a change would be needed to `gatsby-node.js`, but I don't think that file can be shadowed.

**Comment by arshad** [comment]
Yeah. I can take a look at it.

The other themes support subfolders so I think it should be easy to add.
