### ISSUE TITLE
How do I add a logo to the header?

### ISSUE THREAD

**Issue by mattmaker** [reflexjs/reflex#13]
1. Uploaded the file `logo.png` to the `content/images` folder.

2. Added `logo: "/content/images/logo.png"` to the `siteMetaData` in `gatsby-config.js`

3. Opened `content/blocks/header.mdx` and changed the following:
![Screen Shot 2020-07-09 at 5 02 14 PM](https://user-images.githubusercontent.com/3858718/87102193-fd637480-c205-11ea-925d-bc0cf9315009.png)

Instead of displaying the logo, it hides it and the navigation menu moves to the left.

What could I be doing wrong?

**Comment by jacine** [comment]
Hi @mattmaker,

Did you try using the [image component](https://reflexjs.org/docs/images#local-images)? You should be able to use:

```jsx
<Image src="logo.png" alt="Logo" />
```

Let us know how it goes! 

Jacine 🙂

**Comment by mattmaker** [comment]
The image component isn't working with a local path. Only with a URL :(

**Comment by mattmaker** [comment]
Fixed! I realized that the logo image was too big so I just added ` width="100px"` and it works now 😅
