### ISSUE TITLE
Custom theme not working

### ISSUE THREAD

**Issue by mattmaker** [reflexjs/reflex#14]
I created a `theme.js` file in this path `src/@reflexjs/gatsby-theme-base` and copied the example theme into it.

![Screen Shot 2020-07-10 at 3 53 10 PM](https://user-images.githubusercontent.com/3858718/87209222-f439dc80-c2c5-11ea-8f61-1e59a25fc960.png)

But when I change any of the styles, they don't change on the site.

What am I doing wrong?

**Comment by arshad** [comment]
Hmm this looks correct. Did you try a `gatsby clean && gatsby develop`?

**Comment by mattmaker** [comment]
I tried that and it's breaking all the styles of the page like this:

![reflexjs](https://user-images.githubusercontent.com/3858718/87239292-6a236e00-c3c2-11ea-8f09-f6094f5e10f0.png)

**Comment by arshad** [comment]
Oh you need to extend base then. Can you try the following:

```js
import base from "@reflexjs/preset-base"
export default {
  preset: base, <-------------------------
  
// Overrides.
  colors: {
    text: "#000"
    primary: `#07c`,
    ....etc
  },
}
```

See https://reflexjs.org/docs/presets#base

**Comment by arshad** [comment]
Tip: when styling your components, the theme reference page might come in handy: https://reflexjs.org/theme

**Comment by mattmaker** [comment]
That worked! Thanks :)

**Comment by uschtwill** [comment]
Thanks @arshad for this project, this is truly awesome!

> Hmm this looks correct. Did you try a gatsby clean && gatsby develop?

Would you mind adding this to step 7 of the tutorial (https://reflexjs.org/learn/theming)?

**Comment by arshad** [comment]
Thanks. I'll update the docs.
