### ISSUE TITLE
How to add my own custom font in my code

### ISSUE THREAD

**Issue by coolpinkzz** [reflexjs/reflex#17]

**Comment by coolpinkzz** [comment]
i have my own css styled font is there any way to add custom css font in my app?

**Comment by coolpinkzz** [comment]
> i have my own css styled font is there any way to add custom css font in my app?

or i need to add my font  in https://github.com/KyleAMathews/typefaces here ?

**Comment by arshad** [comment]
No you can use self-hosted fonts. Take a look at this plugin: https://www.gatsbyjs.org/packages/gatsby-plugin-web-font-loader/

**Comment by arshad** [comment]
@coolpinkzz did you figure this out?

**Comment by coolpinkzz** [comment]
yes Thanks
