### ISSUE TITLE
Tutorial step 2 (Installation) instructions are slightly wrong

### ISSUE THREAD

**Issue by thefrontendwizard** [reflexjs/reflex#2]
The installation step suggests that after running `gatsby new mysite reflexjs/gatsby-starter-base` you're going to endup with a file structure that looks like this:
```
mysite
├── content
│   ├── blocks
│   ├── images
│   └── pages
├── gatsby-config.js
└── package.json
```
but the content directory only shows up after starting development server...

**Comment by arshad** [comment]
Nice catch. I've updated the docs in https://github.com/reflexjs/reflex/commit/a82afd687a3539ba13ae201716843d5840c8d64b. Thank you.
