### ISSUE TITLE
am not able to setup headway app in my reflexjs app 

### ISSUE THREAD

**Issue by coolpinkzz** [reflexjs/reflex#21]

**Comment by arshad** [comment]
What have you tried so far?

**Comment by coolpinkzz** [comment]
According to Docs  https://docs.headwayapp.co/widget i paste this below code inside head tag and selector as Footer 

<script src="//cdn.headwayapp.co/widget.js"></script>
<script>
  var config = {
    selector: "Footer",
    account: "ACCOUNT_ID"
  };
  Headway.init(config);
</script>

then for styling i paste this below code in theme.js file
var HW_config = {
  selector: ".CHANGE_THIS",
  account: "ACCOUNT_ID",
  translations: {
    title: "The Changelog",
    readMore: "Read more",
    labels: {
      "new": "News",
      "improvement": "Updates",
      "fix": "Fixes"
    },
    footer: "Read more 👉"
  }
};
this much i did i think problem is in selector

**Comment by coolpinkzz** [comment]
also it worked in my react app but not in reflex

**Comment by arshad** [comment]
Can you try `footer` instead of `Footer`? 

If this does not work, you can add an id to the footer and use this as the selector.

```jsx
// content/blocks/footer.mdx
<Footer py="6" id="footer">
  <Container mt="20" textAlign="center">
    <Block src="copyright" />
  </Container>
</Footer>
```

The use `#footer` as the selector.

**Comment by coolpinkzz** [comment]
i tried this but in console it is showing 
![headway](https://user-images.githubusercontent.com/52915014/88775074-e3cca180-d1a1-11ea-833f-aa74bebc44ab.png)

**Comment by arshad** [comment]
OK. I'm going to sign up for a Headway account and test this. I'll let you know.

**Comment by coolpinkzz** [comment]
any updates @arshad  ? please tell how to integrate thirdparty in reflex.js  ?

**Comment by arshad** [comment]
OK I created an account to test this. Seems to be working.

## Step 1: gatsby-ssr.js

Add the following to a file called `gatsby-ssr.js` (root of your site).

```js
import * as React from "react"

export const onRenderBody = ({ setPostBodyComponents }) => {
  setPostBodyComponents([
    <script key="headway-widget" src="https://cdn.headwayapp.co/widget.js" />,
  ])
}
```

## Step 2: gatsby-browser.js

Add the following to `gatsby-browser.js`

```js
const HeadwayConfig = {
  selector: "#branding",
  account: "ACCOUNT_ID_HERE",
}

exports.onInitialClientRender = () => {
  window.Headway.init(HeadwayConfig)
}

exports.onRouteUpdate = () => {
  window.Headway.init(HeadwayConfig)
}
```

I'm using `#branding` as selector here since I added a branding id to my `header.mdx`. This renders the widget next to the site name.

```jsx
export const Branding = ({ ...props }) => {
  const { title } = useSiteMetadata()
  return (
    <A
      href="/"
      fontSize="xl"
      fontFamily="heading"
      color="black"
      hoverColor="black"
      id="branding" <------------------
      {...props}
    >
      {title}
    </A>
  )
}
```

## Preview

![headway](https://user-images.githubusercontent.com/124599/89421297-e7819a80-d744-11ea-9120-8ba66df2ca20.jpg)

**Comment by coolpinkzz** [comment]
Done Thank you so much ❤️

**Comment by arshad** [comment]
You're welcome. I'm going to close this ticket. Feel free to create new ones if you have any other question. Looking forward to your site launch 🚀
