### ISSUE TITLE
📝 pageQuery example

### ISSUE THREAD

**Issue by diederikproot** [reflexjs/reflex#22]
Hello,

I think I stumbled upon a typo in the example query. You can find it on the following URL: https://reflexjs.org/docs/video-configuration

=> the "allvideo" should be "allVideo".

![image](https://user-images.githubusercontent.com/37147506/88854464-98da7a80-d1f1-11ea-988e-20c570b5ce82.png)

**Comment by arshad** [comment]
Nice catch. I updated the docs. Thank you.
