### ISSUE TITLE
📝 blocks video 3 - import container

### ISSUE THREAD

**Issue by diederikproot** [reflexjs/reflex#23]
Hello,

in the following URL : 
https://reflexjs.org/library/blocks/videos-03

the "Container" component is not imported. In source of the block.

(when you copy-paste the ''src/@reflexjs/gatsby-theme-video/videos.js'' file)

![image](https://user-images.githubusercontent.com/37147506/88862371-6f751b00-d200-11ea-9f1b-8c1deed47d37.png)

**Comment by arshad** [comment]
Fixed. Thank you 👍
