### ISSUE TITLE
Avoid Bad Request Problem in GTMetrix

### ISSUE THREAD

**Issue by amanbhattarai4400** [reflexjs/reflex#25]
Yesterday, I deployed my site on Netlify and ran performance testing in GTMetrix. I got this issues: 

![bad request issue](https://user-images.githubusercontent.com/41770152/89100784-d0c40680-d419-11ea-8dc0-b92f7e6bc6ee.png)

Am I missing something?

**Comment by arshad** [comment]
It looks like Gatsby is looking for page `/item-one` and it's not there. Can you check your content (most probably an href) linking to these pages?

**Comment by amanbhattarai4400** [comment]
I didn't find any "href" pointing to above pages. 

However, I think there's some issue with featured post on homepage, because one of the post "7 Tips To Improve Your Writing" has `featured:false` but it is showing up on homepage. I have other 3 posts with `featured:true`

Site is live at : https://mytwistblogg.netlify.app/

Here's the repo link for posts: https://github.com/twistblogg/website/tree/master/content/posts
