### ISSUE TITLE
Add next post and previous post feature

### ISSUE THREAD

**Issue by woosungchoi** [reflexjs/reflex#26]
I like the ability to view the next and previous posts. So it would be nice if reflex also had this feature.

**Comment by arshad** [comment]
You can add this by creating a `post-footer.mdx` block and add the pager there. 

`post-footer.mdx` is a special block that is automatically rendered by the `post-template.js` file. It receives the same props as `post.js`. 

Similarly you can create `posts-header.mdx, posts-footer.mdx, post-header.mdx and post-footer.mdx`. See https://reflexjs.org/docs/blog-custom-page#add-header-and-footer

I've updated the docs with a recipe for previous and next pager: https://reflexjs.org/docs/blog-recipes#previous-and-next-pager

Make sure you're on the latest version: `npm update @reflexjs/gatsby-theme-post`.

**Comment by woosungchoi** [comment]
thx!
