### ISSUE TITLE
Custom NavMenu link styles

### ISSUE THREAD

**Issue by colinrim** [reflexjs/reflex#27]
Any chance to pass custom link-styles such as `color="#ffffff"` all the way down to `<NavMenuLink>`?
Goal would be to to get a custom header with different link-text-colors other to base-theme values.
Thanks for your time.

**Comment by arshad** [comment]
You can do it using the `sx` property for now.

Here I'm setting `a` to be always `black`.

```jsx
<NavMenu
  name={navName}
  sx={{
    color: "black",
    "a, a:hover, a[aria-current=page]": {
      color: "black",
      fontWeight: "semibold",
    },
  }}
/>
```

We are going to break `NavMenu` into smaller components which should make customization a bit easier.

**Comment by arshad** [comment]
You could also shadow `src/@reflexs/gatsby-theme-nav/nav-menu.js` and add the custom styles in there.

**Comment by colinrimann** [comment]
Thanks for your reply. 
Passing `sx` prop with styles does the trick. but this also sets color for `popup-submenus` which is not desirable.
Sorry, what do you mean with `shadowing` the source file out of `node_modules`?
