### ISSUE TITLE
Previous and Next Pager Not Showing Up 

### ISSUE THREAD

**Issue by amanbhattarai4400** [reflexjs/reflex#28]
I am unable to add Prev and Next Pager. I did npm update `@reflexjs/gatsby-theme-post` and followed this guide: 

[https://reflexjs.org/docs/blog-recipes/#previous-and-next-pager](https://reflexjs.org/docs/blog-recipes/#previous-and-next-pager)

![Screenshot 2020-08-03 09:01:05](https://user-images.githubusercontent.com/41770152/89146013-24e1fe80-d572-11ea-99b4-b9dfd9c2fe2e.png)

**Comment by arshad** [comment]
Can you paste in the whole content of `post-footer.mdx`? 

There's an issue in MDX where leaving spaces between lines causes an error. Make sure you don't have spaces between your JSX.

**Comment by amanbhattarai4400** [comment]
```js
export const PostFooter = ({ previous, next }) => (
  <Container maxW="null|null|null|900px">
    <Flexbox justifyContent="space-between">
      {previous && (
        <PagerLink>
          <Span d="flex" alignItems="center">
            <Icon name="arrow-left" mr="2" /> Previous
          </Span>
          <PagerTitle title={previous.title} />
        </PagerLink>
      )}
      {next && (
        <PagerLink ml="auto" textAlign="right" alignItems="flex-end">
          <Span d="flex" alignItems="center">
            Next <Icon name="arrow-right" ml="2" />
          </Span>
          <PagerTitle title={next.title} />
        </PagerLink>
      )}
    </Flexbox>
  </Container>
)

export const PagerLink = ({ link, children, ...props }) => (
  <ButtonLink
    href={link}
    d="flex"
    flexDirection="column"
    alignItems="flex-start"
    bg="transparent"
    rounded="md"
    border="0"
    p="4"
    w="40%"
    hoverBg="muted"
    {...props}
  >
    {children}
  </ButtonLink>
)

export const PagerTitle = ({ title }) => (
  <P
    d="none|none|block"
    mt="4"
    mb="0"
    fontWeight="semibold"
    lineHeight="normal"
  >
    {title}
  </P>
)
```

**Comment by arshad** [comment]
Can you try the following:

```jsx
export const PostFooter = ({ previous, next }) => (
  <Container maxW="null|null|null|900px">
    <Flexbox justifyContent="space-between">
      {previous && (
        <PagerLink href={previous.slug}>
          <Span d="flex" alignItems="center">
            <Icon name="arrow-left" mr="2" /> Previous
          </Span>
          <PagerTitle title={previous.title} />
        </PagerLink>
      )}
      {next && (
        <PagerLink
          href={next.slug}
          ml="auto"
          textAlign="right"
          alignItems="flex-end"
        >
          <Span d="flex" alignItems="center">
            Next <Icon name="arrow-right" ml="2" />
          </Span>
          <PagerTitle title={next.title} />
        </PagerLink>
      )}
    </Flexbox>
  </Container>
)

export const PagerLink = ({ children, ...props }) => (
  <ButtonLink
    d="flex"
    flexDirection="column"
    alignItems="flex-start"
    bg="transparent"
    rounded="md"
    border="0"
    p="4"
    w="40%"
    hoverBg="muted"
    {...props}
  >
    {children}
  </ButtonLink>
)

export const PagerTitle = ({ title }) => (
  <P
    d="none|none|block"
    mt="4"
    mb="0"
    fontWeight="semibold"
    lineHeight="normal"
  >
    {title}
  </P>
)
```

**Comment by amanbhattarai4400** [comment]
Its not showing up yet.

**Comment by amanbhattarai4400** [comment]
I tried to add tags counter following this issue: https://github.com/reflexjs/reflex/issues/29 but the `posts-header.mdx` was not visible as well.

**Comment by arshad** [comment]
Can you try removing `npm remove @reflexjs/gatsby-theme-post` and install it again?

**Comment by amanbhattarai4400** [comment]
I did that and updated `npm update @reflexjs/gatsby-theme-post`, however, I got this error while using `gatsby develop`.


![theme](https://user-images.githubusercontent.com/41770152/89274113-33a6df00-d660-11ea-8baf-ba6f056e6453.png)

Error: 

> Couldn't find the "@reflexjs/gatsby-theme-post" plugin declared in "/home/amanbhattarai/mysite/gatsby-config.js".
> 
> Tried looking for a local plugin in /home/amanbhattarai/mysite/plugins/@reflexjs/gatsby-theme-post.
> 
> Tried looking for an installed package in the following paths:
>  - /home/amanbhattarai/mysite/node_modules/gatsby/dist/bootstrap/load-themes/node_modules/@reflexjs/gatsby-theme-post
>  - /home/amanbhattarai/mysite/node_modules/gatsby/dist/bootstrap/node_modules/@reflexjs/gatsby-theme-post
>  - /home/amanbhattarai/mysite/node_modules/gatsby/dist/node_modules/@reflexjs/gatsby-theme-post
>  - /home/amanbhattarai/mysite/node_modules/gatsby/node_modules/@reflexjs/gatsby-theme-post
>  - /home/amanbhattarai/mysite/node_modules/@reflexjs/gatsby-theme-post
>  - /home/amanbhattarai/node_modules/@reflexjs/gatsby-theme-post
>  - /home/node_modules/@reflexjs/gatsby-theme-post
>  - /node_modules/@reflexjs/gatsby-theme-post
> 
> not finished open and validate gatsby-configs - 0.194s

**Comment by amanbhattarai4400** [comment]
I'm getting this error :

>  ERROR #98123  WEBPACK
> 
> Generating SSR bundle failed
> 
> Unexpected token (17:6)
> 
> File: node_modules/@reflexjs/gatsby-plugin-image/src/image.js:17:6
> 
> not finished Generating image thumbnails - 107.193s

![Screenshot 2020-08-04 15:22:13](https://user-images.githubusercontent.com/41770152/89278936-77044c00-d666-11ea-94ef-3aa12cd0fb51.png)

**Comment by arshad** [comment]
@amanbhattarai4400 Did you figure this out? Did this start happening after the gatsby-theme-post update?

**Comment by amanbhattarai4400** [comment]
I tried every possible options, but none of them seemed to work. Then I created a new Base Starter and shifted everything there, and installed previously installed plugins.

Now, everything runs smoothly, no errors and prev-next pager is showing up as well. Maybe that project got corrupted.

Thanks :)
