### ISSUE TITLE
Unable to install tailwind css

### ISSUE THREAD

**Issue by JonathanPeterRajan** [reflexjs/reflex#29]
Great project! For my plan, I plan to make a box which has buttons containing the tags for the main page of my blog. I am not too familiar with React, so I thought it would be easier if I use Tailwind CSS. However, following the guide on the Gatsby Docs, my installation corrupts the website and shows error messages. 
I would appreciate if you how you would install tailwind or any other css platform / give any other ideas on how I could approach creating a box of tag buttons.

**Comment by arshad** [comment]
Sure. 

Can you paste the error messages here please?

I'll take a look at how we can add Tailwind and update here.

**Comment by JonathanPeterRajan** [comment]
ReferenceError: exports is not defined
./node_modules/@reflexjs/gatsby-plugin-metatags/gatsby-browser.js
node_modules/@reflexjs/gatsby-plugin-metatags/gatsby-browser.js:5

  2 | const withDefaults = require("./options")
  3 | const { MetatagsDebugger } = require("./src/metatags-debugger")
  4 | 
> 5 | exports.wrapPageElement = ({ element }, options) => {
  6 |   const { debug } = withDefaults(options)
  7 |   return (
  8 |     <React.Fragment>

__webpack_require__
/home/jonathan/blogsitev1/webpack/bootstrap:789

  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;

fn
/home/jonathan/blogsitev1/webpack/bootstrap:100

   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {

./.cache/api-runner-browser-plugins.js
/home/jonathan/blogsitev1/.cache/api-runner-browser-plugins.js:2

  1 | module.exports = [{
> 2 |       plugin: require('../node_modules/@reflexjs/gatsby-plugin-metatags/gatsby-browser.js'),
  3 |       options: {"plugins":[]},
  4 |     },{
  5 |       plugin: require('../node_modules/gatsby-plugin-theme-ui/gatsby-browser.js'),

__webpack_require__
/home/jonathan/blogsitev1/webpack/bootstrap:789

  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;

fn
/home/jonathan/blogsitev1/webpack/bootstrap:100

   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {

./.cache/api-runner-browser.js/<
/home/jonathan/blogsitev1/.cache/api-runner-browser.js:1

> 1 | const plugins = require(`./api-runner-browser-plugins`)
  2 | const {
  3 |   getResourcesForPathname,
  4 |   getResourcesForPathnameSync,

./.cache/api-runner-browser.js
http://localhost:8000/commons.js:1013:30
__webpack_require__
/home/jonathan/blogsitev1/webpack/bootstrap:789

  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;

fn
/home/jonathan/blogsitev1/webpack/bootstrap:100

   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {

__webpack_require__
/home/jonathan/blogsitev1/webpack/bootstrap:789

  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;

fn
/home/jonathan/blogsitev1/webpack/bootstrap:100

   97 | 		);
   98 | 		hotCurrentParents = [];
   99 | 	}
> 100 | 	return __webpack_require__(request);
  101 | };
  102 | var ObjectFactory = function ObjectFactory(name) {
  103 | 	return {

0
http://localhost:8000/commons.js:88122:18
__webpack_require__
/home/jonathan/blogsitev1/webpack/bootstrap:789

  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;

(anonymous function)
/home/jonathan/blogsitev1/webpack/bootstrap:856

  853 | 
  854 | 
  855 | // Load entry module and return exports
> 856 | return hotCreateRequire(0)(__webpack_require__.s = 0);
  857 | 

(anonymous function)
http://localhost:8000/commons.js:860:10

**Comment by JonathanPeterRajan** [comment]
Sorry if my issues/questions are dumb, do actually need something like tailwind/bootstrap css to easily make something like this or is it somewhat very doable using reflexjs as well? I have just started learning React, so building something like that feels a bit daunting to me.
![tagsblog](https://user-images.githubusercontent.com/62900297/89216730-d90b7580-d5c2-11ea-9ab4-dbe01e0870ed.png)

**Comment by arshad** [comment]
We can definitely do this in Reflex. Hold on.

**Comment by arshad** [comment]
### Step 1: Create a hook to retrieve post tag data.

Let's create a hook that is going to make a GraphQL query to get the post tags with post count.

Create the following file: `src/use-post-tags.js` with the following:

```js
import { useStaticQuery, graphql } from "gatsby"

export const usePostTag = () => {
  const data = useStaticQuery(graphql`
    query {
      # Find all post tags, return the name and slug fields.
      allPostTag {
        nodes {
          name
          slug
        }
      }
      # Find all posts grouped by the tag slug and return the total count.
      allPost {
        group(field: tags___slug) {
          slug: fieldValue
          totalCount
        }
      }
    }
  `)

  // Loop through the post tags and add the count by matching slugs.
  data.allPostTag.nodes.map(
    (node) =>
      (node.count = data.allPost.group.filter(
        ({ slug }) => slug === node.slug
      )[0].totalCount)
  )

  return data.allPostTag.nodes
}
```

We can now use `usePostTag()` to get an array of tags with the post count.

### Step 2: Create the posts header block

If you create a `posts-header.mdx` block, Reflex will automatically render the content on the `/blog` landing page. See docs: https://reflexjs.org/docs/blog-custom-page#add-header-and-footer

We can use this to add the tags grid.

Create `content/blocks/posts-header.mdx` with the following:

```jsx
import { usePostTag } from "../../src/use-post-tag"

export const PostsHeader = () => {
  const tags = usePostTag()
  if (!tags.length) return null
  return (
    // Container with margin-top.
    // Grid with 2 col on mobile, 4 on tablet and 8 on desktop.
    // Button with white background, padding and hover background color.
    <Container mt="8">
      <Grid col="2|4|8" gap="2" p="4" rounded="md" bg="muted">
        {tags.map((tag) => (
          <ButtonLink
            href={tag.slug}
            key={tag.slug}
            rounded="sm"
            bg="white"
            py="2"
            hoverBg="primary"
          >
            {tag.name}
            <Span bg="muted" py="2" px="3" rounded="sm" ml="2">
              {tag.count}
            </Span>
          </ButtonLink>
        ))}
      </Grid>
    </Container>
  )
}
```

We are using `usePostTag()` to get the post tags and render them in a grid.

If you refresh your blog page, you should see the tags list rendered above.

![The_Wildlife_Blog___Megan_Morales](https://user-images.githubusercontent.com/124599/89221324-264c0f00-d5e4-11ea-94be-4bcf1459857a.jpg)
### Tailwind and Reflex

If you're familiar with Tailwind, Reflex should be easy to understand. Tailwind uses classes. Reflex uses props. 

Here's a quick overview/mapping:

### Tailwind

```
// Tailwind
<div class="bg-red px-2 rounded-sm" /> sets the background to red, padding 2 and sm borderRadius

// Reflex
<Div bg="red" px="2" rounded="sm" />
```

```
// Tailwind
<div class="mt-2 md:mt-4 lg:mt-8" /> sets the margin top to 2 for mobile, 4 for tablet and 8 for desktop.

// Reflex
<Div mt="2|4|8" />
```

You can learn more in the theme reference: https://reflexjs.org/theme

**Comment by JonathanPeterRajan** [comment]
Hi, thank you so much for your support. I now have a working tags menu! Also, I have realised that the styling on Reflex is good enough that there is not much point going through the hassle to install tailwind. Thank you once again.

**Comment by JonathanPeterRajan** [comment]
Hi, I used this post block -> https://reflexjs.org/library/blocks/posts-02
After following the steps, after I click on a post from the blog page an error comes up
![Screenshot_2020-08-03 Reflex Reflex](https://user-images.githubusercontent.com/62900297/89232345-2ac1f900-d5df-11ea-8753-41c958e0b805.png)

Also, the tags menu box disappears. 
![Screenshot_2020-08-03 Reflex Reflex(1)](https://user-images.githubusercontent.com/62900297/89232411-504f0280-d5df-11ea-9da8-6a1bbbb91128.png)

I would greatly appreciate your help once again.

**Comment by arshad** [comment]
It looks like you're setting a custom slug for the post? Can you try going to `/title-of-the-post.html` and check if you can see the blog post?

**Comment by JonathanPeterRajan** [comment]
I added this to the slugresolver inn the gatsby-config.js file :         slugResolver: (node, parent, basePath) =>
        `${toSlug(node.frontmatter.title)}.html`,
I did that since otherwise only the tags writing and stories would show up in the tag counter. If I go to my post.mdx file and change the tag to something else, I get an error.

I went to /title-of-the-post.html and it foes show the blog post

**Comment by arshad** [comment]
I see. If you're providing your own `slugResolver` there are some gotchas you'll need to watch for. 

If everything is looking good here, let's close this issue.

Feel free to open new one if you have any other question.
