### ISSUE TITLE
Tutorial step 6 also has problems with background on dark mode

### ISSUE THREAD

**Issue by thefrontendwizard** [reflexjs/reflex#3]
https://reflexjs.org/learn/styling

![image](https://user-images.githubusercontent.com/1124448/85119904-c1e71300-b222-11ea-811a-446dcff1ebab.png)

**Comment by arshad** [comment]
Fixed in https://github.com/reflexjs/reflex/commit/a82afd687a3539ba13ae201716843d5840c8d64b. Thank you.
