### ISSUE TITLE
Add Related Post Feature

### ISSUE THREAD

**Issue by amanbhattarai4400** [reflexjs/reflex#32]
I tried to create a related post widget below every post by following the guidance from previous-next pager feature. However, I couldn't extract anything. Can you please show me how to achieve this? 

Since, we can add multiple tags in a post, generating related articles can be tricky. However, I'll be fine to generate based on first tag.

Here's what I'm expecting:

![relatedpost](https://user-images.githubusercontent.com/41770152/89373026-5e983e00-d707-11ea-9d8d-2d298cc0be0e.png)

**Comment by arshad** [comment]
So you want a block with posts under the same tag? Sort by date and take the top 3?

**Comment by amanbhattarai4400** [comment]
It will be a related posts plugin and I'm planning to place it at the end of every posts. So, it will filter articles based on first tag (if multiple present) and display as "Recommended Articles". 

Here's an example, https://later.com/blog/brands-on-instagram-reels/ (Scroll down till you reach **You may also like** )

And please a full width display.

It can be a "post-footer.mdx" blog.

**Comment by arshad** [comment]
OK let's give this a try:

## Step 1: Create `related-posts.mdx` block

We retrieve all posts using `usePost` then we filter the posts with similar tags and filter out the one with same slug (to not show the post we are viewing).

```jsx
import { usePost } from "@reflexjs/gatsby-theme-post"

export const RelatedPosts = ({ slug, tags }) => {
  const posts = usePost()
  const tagsName = tags.map(({ name }) => name)
  const relatedPosts = posts.filter(
    ({ slug: postSlug, tags }) =>
      tags.filter(({ name }) => tagsName.includes(name)).length &&
      slug !== postSlug
  )
  if (!relatedPosts.length) return null
  return (
    <Section my="10">
      <H3 textAlign="center" mb="8" fontSize="3xl">
        You may also like
      </H3>
      <Grid col="1|2|2|3" maxW="1200" mx="auto" gap="10">
        {relatedPosts.map((post) => (
          <Article key={post.slug}>
            <Link to={post.slug} d="block">
              <Image src={post.image} />
            </Link>
            <H4 mt="4" mb="0" fontSize="xl" lineHeight="normal">
              <Link to={post.slug}>{post.title}</Link>
            </H4>
            {post.excerpt && (
              <P fontSize="md" mt="2">
                {post.excerpt}
              </P>
            )}
            <Link
              to={post.slug}
              color="text"
              fontSize="md"
              d="flex"
              lineHeight="1"
            >
              Read more <Icon name="arrow-right" size="4" ml="2" />
            </Link>
          </Article>
        ))}
      </Grid>
    </Section>
  )
}
```

## Step 2: Create `post-footer.mdx` block

We call our related posts block in the post footer and pass the slug and tags to it.

```jsx
export const PostFooter = ({ slug, tags }) => (
  <Block src="related-posts" slug={slug} tags={tags} />
)
```

## Demo

<img width="1343" alt="The_Wildlife_Blog___Megan_Morales" src="https://user-images.githubusercontent.com/124599/89504168-aa66e800-d7d8-11ea-860f-8ba226db11d1.png">

**Comment by amanbhattarai4400** [comment]
First of all, thank you so much. It is working but I have some few queries:

1) So sometimes a tag auto disappear from blog post and I need to do `gatsby clean` for getting it back. I noticed this feature generates an error "**Cannot read property map of null**" when tags are not visible. Can we overcome that ?  Maybe it has to do something with this line :  `if (!relatedPosts.length) return null` I'm not sure. 

2) It is generating all posts, can we trim the result to `max=6`? Like it will only show random 6 related posts.

3) I wanted to set same height for all images so it will look parallel. I tried using `h=250px` but the image got zoomed in, though it is working.

4) How much will this feature has impact on page speed? Because a lot of images will be loaded, but gatsby does auto lazy loading. Can you give a brief please?

Thank you and Stay Safe.

**Comment by arshad** [comment]
I've updated the code:

1. Added a check for empty tags.
2. Added a `limit` props with default.
3. You can do this using `aspectRatio`. See https://reflexjs.org/docs/images#aspect-ratio
4. Gatsby will handle this for you using a few techniques including lazy loading.

## Updated code

```jsx
import { usePost } from "@reflexjs/gatsby-theme-post"

export const RelatedPosts = ({ slug, tags, limit = 3 }) => {
  const posts = usePost()
  if (!tags.length) return null
  const tagsName = tags.map(({ name }) => name)
  const relatedPosts = posts.filter(
    ({ slug: postSlug, tags }) =>
      tags.filter(({ name }) => tagsName.includes(name)).length &&
      slug !== postSlug
  )
  if (!relatedPosts.length) return null
  return (
    <Section my="10">
      <H3 textAlign="center" mb="8" fontSize="3xl">
        You may also like
      </H3>
      <Grid col="1|2|2|3" maxW="1200" mx="auto" gap="10">
        {relatedPosts.splice(0, limit).map((post) => (
          <Article key={post.slug}>
            <Link to={post.slug} d="block">
              <Image src={post.image} aspectRatio={16 / 9} />
            </Link>
            <H4 mt="4" mb="0" fontSize="xl" lineHeight="normal">
              <Link to={post.slug}>{post.title}</Link>
            </H4>
            {post.excerpt && (
              <P fontSize="md" mt="2">
                {post.excerpt}
              </P>
            )}
            <Link
              to={post.slug}
              color="text"
              fontSize="md"
              d="flex"
              lineHeight="1"
            >
              Read more <Icon name="arrow-right" size="4" ml="2" />
            </Link>
          </Article>
        ))}
      </Grid>
    </Section>
  )
}
```

**Comment by amanbhattarai4400** [comment]
Thanks but I'm getting this error now,

**Cannot read property "length" of null**

![Screenshot (1)](https://user-images.githubusercontent.com/41770152/89525333-c0d76880-d805-11ea-9889-9a32be3c3dc0.png)

**Comment by arshad** [comment]
Remove .length `if (!tags) return null`

**Comment by amanbhattarai4400** [comment]
It didn't showed any errors now, however, related posts are not visible.

**Comment by amanbhattarai4400** [comment]
Every-time I need to perform `gatsby clean` for tags and this features to be visible. Maybe that's some bug -- tags auto disappearing.
