### ISSUE TITLE
ScrollBar Color Changing Based on Mode Toggle

### ISSUE THREAD

**Issue by amanbhattarai4400** [reflexjs/reflex#33]
I am able to change scrollbar color with external CSS code, however, I want to change scrollbar color based on light and dark mode. I saw https://www.cassie.codes/ and she has managed to achieve this. 

Is it possible in ReflexJS?

**Comment by arshad** [comment]
Yes you can do this.

```js
export default {
  preset: base,

  colors: {
    // other colors...
    scrollbarColor: "#2b59c3",
    modes: {
      dark: {
       // other dark mode colors...
        scrollbarColor: "#fa2000",
      },
    },
  },

  styles: {
    root: {
      "::-webkit-scrollbar": {
        width: "10px",
      },
      "::-webkit-scrollbar-thumb": {
        backgroundColor: "scrollbarColor",
      },
    },
  },
}
```

PS: It's just Reflex no JS :D

**Comment by amanbhattarai4400** [comment]
Wow, never realized it was that simple playing with CSS. Thanks, it worked :)
