### ISSUE TITLE
@reflexjs/gatsby-plugin-metatags not functioning properly

### ISSUE THREAD

**Issue by amanbhattarai4400** [reflexjs/reflex#34]
I recently transferred my project to new starter and installed previous plugins. However, `gatsby-plugin-metatags` seems to not functioning properly.

This is one of my post and when I turned on `debug:true`, I noticed it is taking default title.

![Screenshot](https://user-images.githubusercontent.com/41770152/89401744-7f778800-d735-11ea-98bd-e4a1738ce0b3.png)

Here's my config file for this plugin,

```
{
      resolve: "@reflexjs/gatsby-plugin-metatags",
      options: {
        debug:true,
        global: {
          title: "TwistBlogg - Get Premium Blogger Tutorials",
          description: "TwistBlogg is an information resource site for Bloggers and Geeks.Here we focus on SEO, Blogging, Blogging Widgets, Tips and Tricks related to Social Media and Web Apps.",
          image: "social media.webp",
        },
        types: [
          `Page`,
          `Post`,
          {
            type: `PostTag`,
            defaults: {
              title: (tag) => {tag.name},
            },
          },
        ],
        paths: [
          {
            pathname: `/blog{,/**}`,
            defaults: {
              title: `Blog | TwistBlogg - Get Premium Blogger Tutorials`,
            },
          },
        ],
      }
    },
```

Also, lighthouse testing reveals **meta description** is missing. I've set my site description as well,

```
siteMetadata: {
    title: "TwistBlogg",
    description: "TwistBlogg is an information resource site for Bloggers and Geeks.Here we focus on SEO, Blogging, Blogging Widgets, Tips and Tricks related to Social Media and Web Apps.",
    siteUrl: process.env.SITE_URL || "http://localhost:8000",
  },
```

**Comment by arshad** [comment]
Ah this is a known bug (regression probably). We are working on fixing this. 

For now you can fix this by prefixing your `types` with `Mdx`. Example: `MdxPage`, `MdxPost` ...etc

**Comment by amanbhattarai4400** [comment]
Yea, that seems to fix the issue. Thanks :) Once any update is out for this bug, please re-open and notify.
