### ISSUE TITLE
Change width of theme

### ISSUE THREAD

**Issue by mattmaker** [reflexjs/reflex#36]
How can I change the width of the entire theme?

I tried looking for a `<Container>` component to shadow but couldn't find one.

**Comment by arshad** [comment]
You can change/style any component in your `theme.js` file as follows:

(Use the component name in lowercase: `Container` = `container` and `H1` = `h1`)

```js
import base from "@reflexjs/preset-base"
import "typeface-prata"

export default {
  preset: base,

  colors: {
    primary: "#fee440",
    secondary: "#07070a",
  },

  container: {
    // Default container width.
    width: "1200px",

    // <Container variant="sm" />
    sm: {
      width: "900px",
    },

    // <Container variant="lg" />
    lg: {
      width: "1600px",
    },
  },

  // Set the styles for all h1
  h1: {
    fontFamily: "heading",
    fontWeight: 400,
  },
}
```

This is called variants. You can read more on variants in the doc: https://reflexjs.org/docs/theming-styling#variants

**Comment by mattmaker** [comment]
Thanks!
