### ISSUE TITLE
Easy way to insert Customized Tables

### ISSUE THREAD

**Issue by amanbhattarai4400** [reflexjs/reflex#37]
Hello,

I've been using external CSS file to style table currently. Is there any easy way to dynamically insert a table with customized design? Something like a block and insert values dynamically?

**Comment by arshad** [comment]
You can either use Markdown tables and style those in your `theme.js` file:

```js
export default {
  preset: base,

  table: {
    bg: "primary",

    td: {
        borderWidth: 1,
    }
  }
}
```

or create a block and add the styles on the block like this: https://codesandbox.io/s/jolly-surf-rdses?file=/content/pages/index.mdx

**Comment by amanbhattarai4400** [comment]
Thank you. It was helpful.
