### ISSUE TITLE
Generating SSR bundle failed

### ISSUE THREAD

**Issue by JonathanPeterRajan** [reflexjs/reflex#40]
During gatsby develop, I got this error
 ERROR #98123  WEBPACK

Generating SSR bundle failed

Unexpected token (17:6)

File: node_modules/@reflexjs/gatsby-plugin-image/src/image.js:17:6

not finished Generating image thumbnails - 40.267s

I have tried doing gatsby clean but the problem persists

File: node_modules/@reflexjs/gatsby-plugin-image/src/image.js:17:6 
import * as React from "react"
import GatsbyImg from "gatsby-image"
import { isRelativeUrl } from "@reflexjs/utils"
import { Img, Figure, Figcaption } from "@reflexjs/components"
import { useImage } from "./use-image"

export const Image = ({ src, alt, title, caption, aspectRatio, ...props }) => {
  const [image] = useImage(src)

  props = {
    m: 0,
    ...props,
  }

  const Caption = () =>
    caption ? (
      <Figcaption
        dangerouslySetInnerHTML={{ __html: caption }}
        mt="2"
        textAlign="center"
        fontSize="md"
      />
    ) : null

  // Return Gatsby image if fixed or fluid is passed.
  if (props.fixed || props.fluid) {
    return (
      <Figure {...props}>
        <GatsbyImg {...props} alt={alt} title={title} />
        <Caption />
      </Figure>
    )
  }

  if (!src) return null

  // Return default image tag if absolute src.
  if (!isRelativeUrl(src)) {
    return (
      <Figure {...props}>
        <Img src={src} alt={alt} title={title} {...props} />
        <Caption />
      </Figure>
    )
  }

  return image ? (
    <Figure {...props}>
      {aspectRatio ? (
        <GatsbyImg
          sizes={{
            ...image.childImageSharp.fluid,
            aspectRatio,
          }}
          alt={alt}
          title={title}
        />
      ) : (
        <GatsbyImg
          fluid={image.childImageSharp.fluid}
          alt={alt}
          title={title}
        />
      )}
      <Caption />
    </Figure>
  ) : null
}

**Comment by arshad** [comment]
Seems to be a common issue. Can you try removing `node_modules` and run `npm install` or `yarn` again?

**Comment by amanbhattarai4400** [comment]
I won't consider this as solution, however, I had to shift my whole project in new directory and the error was resolved.

**Comment by JonathanPeterRajan** [comment]
Hi, thank you both for the suggestion.
I tried removing node_modules and running npm install first and it fixed my problem.
