### ISSUE TITLE
Is it possible to use reflex components/blocks on a gatsby website that wasnt originally made with reflex starter base?

### ISSUE THREAD

**Issue by JonathanPeterRajan** [reflexjs/reflex#52]

**Comment by arshad** [comment]
Yes you can.

1. Install dependencies: `npm i theme-ui gatsby-plugin-theme-ui @reflexjs/components @reflexjs/preset-base typeface-inter`
2. Create the following file: `src/gatsby-plugin-theme-ui/index.js` and add the following code:

```js
import theme from "@reflexjs/preset-base"

export default {
  ...theme,

  // Overrides here.
}
```

You can now use Reflex components on your pages:

```jsx
import React from "react"
import { H1 } from "@reflexjs/components"

export default () => (
  <H1 color="primary" mb="10">Heading One</H1>
)
```

Here's an example codesandbox: https://codesandbox.io/s/zen-shadow-uf41h?file=/src/pages/index.js

**Comment by JonathanPeterRajan** [comment]
That's excellent! Thanks!
If I were to use the premade blocks found on the website, do I still need to put them in a folder called Blocks?

**Comment by arshad** [comment]
No you can drop them in your pages: `src/pages/example.js`.

**Comment by JonathanPeterRajan** [comment]
Ok, thank you for the help!
