### ISSUE TITLE
Custom fonts

### ISSUE THREAD

**Issue by Lokdex** [reflexjs/reflex#63]
Hello,

I'm wondering if there is any way to use custom fonts downloaded and added to the project directory either to /src or /static, because so far all the documentation is Gatsby specific, and in Reflex I have seen no way to import the custom font.css with the font-face declared. Or is there any other way to do so directly in reflex?

**Comment by arshad** [comment]
Sure. Are you using a framework such as Gatsby or Next?

**Comment by Lokdex** [comment]
Yes, I'm using Gatsby.

**Comment by arshad** [comment]
Can you check if this thread helps? #17

**Comment by Lokdex** [comment]
Will check it now.

**Comment by Lokdex** [comment]
Yes, I followed up more or less the same steps, but I'm stuck at the moment of actually using the declared font.
My Gatsby-config.js looks like this:

```
module.exports = {
   siteMetadata: {
      title: "Simbiosis",
      description: "Página web de Simbiosis.",
      siteUrl: process.env.SITE_URL || "http://localhost:8000",
   },
   plugins: [
      "@reflexjs/gatsby-theme-base",
      {
         resolve: "gatsby-source-filesystem",
         options: {
            name: "fonts",
            path: `${__dirname}/static/fonts/`,
         },
      },
      {
        resolve: "gatsby-plugin-web-font-loader",
        options: {
          custom: {
            families: ["Rounded"],
            urls: ["/static/fonts/fonts.css"],
          },
        },
      },
   ],
};

```
The font I downloaded is placed at /static/fonts, as well as the fonts.css, which looks like this:
```
@font-face {
    font-family: "Rounded";
    src: url("Rounded_Elegance.ttf") format("ttf");
  }
```

**Comment by arshad** [comment]
I created an example repo here. Can you take a look and see if this works for you?

https://github.com/arshad/reflex-custom-fonts

Demo: https://reflex-custom-fonts.netlify.app

**Comment by Lokdex** [comment]
Holy smokes, yes, that did it. thank you so very much. What I was missing was importing the css in the Gatsby-browser.js.
Thanks for the assistance once again. Have a nice day.

**Comment by arshad** [comment]
Awesome.
