### ISSUE TITLE
Issue in build

### ISSUE THREAD

**Issue by Abhikumar98** [reflexjs/reflex#65]
![Screenshot 2020-09-03 at 9 22 16 AM](https://user-images.githubusercontent.com/35174288/92069553-43ccee00-edc7-11ea-9fff-fe378951e6de.png)

9:18:19 AM: failed Building production JavaScript and CSS bundles - 69.173s
9:18:19 AM: error Generating JavaScript bundles failed
9:18:19 AM: /opt/build/repo/node_modules/@reflexjs/gatsby-plugin-image/src/image.js: Support for the experimental syntax 'jsx' isn't currently enabled (17:7):
9:18:19 AM:   15 |   const Caption = () =>
9:18:19 AM:   16 |     caption ? (
9:18:19 AM: > 17 |       <Figcaption
9:18:19 AM:      |       ^
9:18:19 AM:   18 |         dangerouslySetInnerHTML={{ __html: caption }}
9:18:19 AM:   19 |         mt="2"
9:18:19 AM:   20 |         textAlign="center"
9:18:19 AM: Add @babel/preset-react (https://git.io/JfeDR) to the 'presets' section of your Babel config to enable transformation.
9:18:19 AM: If you want to leave it as-is, add @babel/plugin-syntax-jsx (https://git.io/vb4yA) to the 'plugins' section to enable parsing.
9:18:19 AM: not finished Generating image thumbnails - 73.171s
9:18:20 AM: (sharp:1503): GLib-CRITICAL **: 03:48:20.481: g_hash_table_lookup: assertion 'hash_table != NULL' failed
9:18:20 AM: ​
9:18:20 AM: ┌─────────────────────────────┐
9:18:20 AM: │   "build.command" failed    │
9:18:20 AM: └─────────────────────────────┘
9:18:20 AM: ​
9:18:20 AM:   Error message
9:18:20 AM:   Command failed with exit code 1: gatsby build
9:18:20 AM: ​
9:18:20 AM:   Error location
9:18:20 AM:   In Build command from Netlify app:
9:18:20 AM:   gatsby build
9:18:20 AM: ​
9:18:20 AM:   Resolved config
9:18:20 AM:   build:
9:18:20 AM:     command: gatsby build
9:18:20 AM:     commandOrigin: ui
9:18:20 AM:     publish: /opt/build/repo/public

This issue randomly comes and goes.

I've added @babel/preset-react and @babel/plugin-syntax-jsx to the gatsby's config file but still, it's happening.

**Comment by arshad** [comment]
I've seen this bug too. I'll take a look at it and get back to you. Thanks.

**Comment by mattmaker** [comment]
I'm having the same problem :(

Tried a fresh install of Reflex and it happened again.

**Comment by arshad** [comment]
I haven't been able to successfully reproduce this. This happens on `gatsby build`? Can you try updating `gatsby-cli` and try again? `npm i -g gatsby-cli`

**Comment by arshad** [comment]
@Abhikumar98 @mattmaker any luck? Did the above work?

**Comment by Abhikumar98** [comment]
Yes, this did the work for me.
Thanks @arshad

**Comment by arshad** [comment]
Thanks @Abhikumar98. Going to close this as fixed.

@mattmaker Please re-open if you're still seeing this issue. Thank you.
