### ISSUE TITLE
Not able to trigger event onChange event on input

### ISSUE THREAD

**Issue by Archish27** [reflexjs/reflex#67]
@arshad Hello I am not able to perform onChange event on form? 
Does it have any example where we can refer for reflexjs?

**Comment by arshad** [comment]
I added an example here: https://codesandbox.io/s/old-meadow-2jbw3?file=/content/blocks/contact-form.mdx

See the `https://2jbw3.sse.codesandbox.io/contact` page and the `content/blocks/contact-form.mdx` block.

**Comment by Archish27** [comment]
Thanks :+1:
