### ISSUE TITLE
Performance Score Issue - LightHouse Report

### ISSUE THREAD

**Issue by amanbhattarai4400** [reflexjs/reflex#79]
Few days ago, my site was scoring 90+ on light house testing. Today, I checked it back and to my surprise, score was 73. Is there any way to improve it? Here's the screenshot : 

![DeepinScreenshot_select-area_20200913212246](https://user-images.githubusercontent.com/41770152/93022211-c3e52600-f607-11ea-9dba-0a0da1d090c2.png)

**Comment by arshad** [comment]
It seems like Google made some changes to their metric in the latest Lighthouse. This is being discussed here: https://github.com/gatsbyjs/gatsby/issues/24332

There are some helpful pointers in the thread.

**Comment by arshad** [comment]
I'm going to close this issue for now since there's not much we can do in Reflex do fix this. If there's a fix in Gatsby and we need to port to Reflex, I'll reopen and update. Thank you.
