### ISSUE TITLE
Change <img /> on light/dark mode

### ISSUE THREAD

**Issue by mattmaker** [reflexjs/reflex#88]
I have a logo in my header like this:

```
<A href="/">
    <img src="logo-black.png" alt="Logo" />
</A>
```

It's a black logo on a white background. I'd like to switch to `logo-white.png` when I click the button for dark mode.

What is the best way to do this?

**Comment by arshad** [comment]
You can use the `useColorMode` hook to retrieve the active color mode and then set the image based on the value.

```js
import { useColorMode } from "@reflexjs/gatsby-theme-core"

export const Logo = ({ ...props }) => {
  const [colorMode, setColorMode] = useColorMode()
  return (
    <A href="/">
      <img src={`logo-${colorMode === "default" ? "white" : "black"}`} alt="Logo" />
    </A>
  )
}
```

**Comment by mattmaker** [comment]
That didn't exactly work so I changed the code in the `<img />` tag to this:

```
<img src={colorMode === "default" ? "logo-black.png" : "logo-white.png"} alt="Logo" />
```

Works fine now. Thanks!
