### ISSUE TITLE
Icon List

### ISSUE THREAD

**Issue by LocTran016** [reflexjs/reflex#99]
Would you mind adding the icon list to the doc:

![image](https://user-images.githubusercontent.com/64778285/96905547-c79b8080-14c2-11eb-865f-48d906e26758.png)

![image](https://user-images.githubusercontent.com/64778285/96905596-d97d2380-14c2-11eb-800f-39d80c35b266.png)

Thanks

**Comment by arshad** [comment]
The base theme uses Feather icons. You can see a list of the icons here: https://feathericons.com
